### ISSUE TITLE
cost = dlib::join_cols(cost, dlib::zeros_matrix<int>(cost.nc() - cost.nr(), 1));

### ISSUE THREAD

**Issue by xiakj** [samuelmurray/tracking-by-detection#14]
when run demo, the bug is:
DLIB_ASSERT(a.nc() == b.nc() || a.size() == 0 || b.size() == 0,
            "\tconst matrix_exp join_cols(const matrix_exp& a, const matrix_exp& b)"
            << "\n\tYou can only use join_cols() if both matrices have the same number of columns"
            << "\n\ta.nr(): " << a.nr()
            << "\n\tb.nr(): " << b.nr()
            << "\n\ta.nc(): " << a.nc()
            << "\n\tb.nc(): " << b.nc()
            );
have you ever seen this bug?

**Comment by samuelmurray** [comment]
Sorry, this is not something I recognize on the top of my head. So maybe you have the wrong version of something, or have some invalid input data.

On 4 Mar 2020, at 14:09, xiakj <notifications@github.com> wrote:

﻿

when run demo, the bug is:
DLIB_ASSERT(a.nc() == b.nc() || a.size() == 0 || b.size() == 0,
"\tconst matrix_exp join_cols(const matrix_exp& a, const matrix_exp& b)"
<< "\n\tYou can only use join_cols() if both matrices have the same number of columns"
<< "\n\ta.nr(): " << a.nr()
<< "\n\tb.nr(): " << b.nr()
<< "\n\ta.nc(): " << a.nc()
<< "\n\tb.nc(): " << b.nc()
);
have you ever seen this bug?

**Comment by xiakj** [comment]
@samuelmurray ok, I will check the dlib and code.
