### ISSUE TITLE
can this project apply on the mobile?

### ISSUE THREAD

**Issue by GeneralJing** [samuelmurray/tracking-by-detection#16]

**Comment by samuelmurray** [comment]
I guess if you compile it for a specific device, you could get it running on a mobile device. I don't think performance should be an issue, though I'm not sure how much effort it would be to get it running at all.
However, I'm sure the field has advanced rapidly since this project, so my guess is that there are better alternatives and more "plug-and-play" solutions out there.

**Comment by GeneralJing** [comment]
thank you for your advice.I tried some methods, either too simple, the effect is not very good, or too many restrictions, not suitable for deployment on the mobile terminal.
