### ISSUE TITLE
Can we use without GPU / CUDA dependency ?

### ISSUE THREAD

**Issue by MyraBaba** [samuelmurray/tracking-by-detection#9]
Can we use without GPU / CUDA dependency ?

how?

**Comment by samuelmurray** [comment]
If you only run the tracking (not detection), you can use the code without cuda or caffe. Otherwise, you would need to change the code to get it to work. I dont know how.

On 14 Apr 2018, at 13:40, MyraBaba <notifications@github.com<mailto:notifications@github.com>> wrote:


Can we use without GPU / CUDA dependency ?

how?
